# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Jacob Ortega
title: Full-Stack Web Developer
email: jakeniaya@gmail.com
website: 19jake68.github.io

# Social links
# twitter_username: 19jake68
github_username:  19jake68
# dribbble_username: jekyll
facebook_username: 19jake68
# flickr_username: jekyll
instagram_username: jakeography12
linkedin_username: jacob-ortega-706241b7
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jake, I'm a full stack web developer with over 7 years experience, based in the Philippines. I am currently working for RCG Global Services as an IT Consultant and my current project is on Walt Disney.

  I enjoy making clean and interactive UI that is quick and easy to use whilst also giving users an enjoyable experience. I have worked with a range of different languages and frameworks and I am always looking for opportunities to work with something new. The things that I currently have the most experience working with are: <mark>ES6 Javascript</mark>, <mark>Angular & NodeJS</mark>, <mark>PHP5/7</mark>, <mark>MySQL & MongoDB</mark>, <mark>HTML5, CSS3, JavaScript</mark>, <mark>SASS/LESS</mark>, <mark>git</mark> and <mark>AWS</mark> services.
  
  As well as making web apps I also have experience in administering linux servers, and creating hybrid mobile and desktop apps, managing and leading a team of front-end developers.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Mountain Climbing
   - Gaming
   - Home Automation Newbie

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
