# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Jacob Ortega
title: Full-Stack Web Developer
email: jakeniaya@gmail.com
website: 19jake68.github.io

# Social links
# twitter_username: 19jake68
github_username:  19jake68
# dribbble_username: jekyll
facebook_username: 19jake68
# flickr_username: jekyll
instagram_username: jaketography12
linkedin_username: jacob-ortega-706241b7
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jake and I'm a full-stack web developer. A professional with 7 years of IT experience.
  <ul>
    <li>Strong Web Development Experience</li>
    <li>Proficient in <mark>PHP</mark>, <mark>MySQL</mark>, <mark>HTML5</mark>, <mark>CSS3</mark>, <mark>JavaScript</mark>, <mark>Angular</mark>, <mark>PolymerJS</mark>, <mark>NodeJS</mark> and <mark>React.</mark></li>
    <li>Experienced in various AWS Cloud Products like <mark>EC2</mark>, <mark>RDS</mark>, <mark>DynamoDB</mark>, <mark>S3</mark>, <mark>Route53</mark>, <mark>VPC</mark>, <mark>Lambda</mark>, <mark>Elastic Beanstalk.</mark></li>
    <li>Responsible of leading a team of web developers.</li>
    <li>Responsible for the quality of project's technical deliverable.</li>
    <li>Providing guidance to other team members on web development issues</li>
  </ul>
  As well as making web apps I also have experience in administering linux servers, and creating hybrid mobile and desktop apps.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Mountain Climbing
   - Gaming
   - Home Automation Newbie

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
